#!/usr/bin/python

#
# Watchdog script to monitor processes. Uses plugin system for each monitor.
# Note: it's self contained (1 file) on purpose for easier deployment.
#

import sys, os, time, atexit
import ConfigParser
import optparse
import logging
from logging import handlers
import psutil, subprocess
import datetime

FULLFORMAT = "%(asctime)s  [%(levelname)s]  [%(module)s] %(message)s"
logger = logging.getLogger("watchdog")
CPUTIME = 60

class WatchdogPlugin(object):
    @staticmethod
    def getPlugin(plugin, name, proc, threshold, cmd):
        plugins = {'mem' : MemoryPlugin, 'cpu' : CpuPlugin }
        try:            
            return plugins[plugin](name, proc, threshold, cmd)
        except KeyError, e:
            logger.error(e)
            raise Exception("Plugin %s does not exist" % plugin)

    def __init__(self, name, proc, threshold, cmd):
        self.name = name
        self.proc = proc
        self.threshold = threshold
        self.cmd = cmd

    def run(self):
        logger.debug("checking %s: %s" % (self.name, self.proc.pid))
        if self.check(self.threshold):
            logger.info("%s reached threshold", self.name)
            self.launcher(self.cmd)
            logger.info("%s triggered", self.name)

    def check(self, value):
        pass

    def launcher(self, cmd):
        cmdargs = cmd.split(" ")
        subprocess.call(cmdargs)

class CpuPlugin(WatchdogPlugin):
    def check(self, threshold):
        # blocking call:
        cpu = self.proc.get_cpu_percent(CPUTIME)
        logger.debug("cpu: %s, threshold: %s" % (cpu, threshold))
        return cpu > threshold

class MemoryPlugin(WatchdogPlugin):
    def human(self, num, power="MB"):
        powers = ["KB", "MB", "GB", "TB"]        
        for i in powers:
            num /= 1024.0
            if power == i:
                break
        return (float(num), power)

    def check(self, threshold):
        (memrss, memvss) = self.proc.get_memory_info() # memory in bytes
        try:
            (mem, frmt) = threshold.split(" ") # (X, KB), (X, MB), ...
        except ValueError:
            (mem, frmt) = (threshold, "KB")
        
        mem = float(mem)
        memrss = self.human(memrss, frmt)
        memvss = self.human(memvss, frmt)
        hmemrss = "%.1f %s" % memrss
        hmemvss = "%.1f %s" % memvss

        logger.debug("mem: %s, %s, threshold: %s" % (hmemrss, hmemvss, threshold))                            
        return memrss[0] > mem

class Watchdog(object):
    """Watchdog
    """

    def __init__(self, settings):
        if not os.path.isfile(settings):
            raise Exception("%s doesn't exist or is not a regular file" % settings)
        self.settings = ConfigParser.ConfigParser()
        self.settings.read(settings)
        self.wait = self.settings.getint("DEFAULT", "wait")
        logger.debug("timer set to %s" % datetime.timedelta(seconds=self.wait))

    def run(self):
        logger.info("running watchdog")
        while True:
            programs = self.settings.sections()
            for program in programs:
                name = self.settings.get(program, "name")
                pluginname = self.settings.get(program, "plugin")
                threshold = self.settings.get(program, "value")
                cmd = self.settings.get(program, "cmd")

                for pid in psutil.get_pid_list():
                    try:
                        proc = psutil.Process(pid)
                        if name in " ".join(proc.cmdline):
                            # create plugin and execute it
                            plugin = WatchdogPlugin.getPlugin(pluginname, name, proc, threshold, cmd)
                            plugin.run()
                    except psutil.error.NoSuchProcess:
                        logger.debug("NoSuchProcess: %s" % pid)
            time.sleep(self.wait)

def daemonize():
    # http://code.activestate.com/recipes/66012/
    # do the UNIX double-fork magic, see Stevens" "Advanced 
    # Programming in the UNIX Environment" for details (ISBN 0201563177)
    try:
        pid = os.fork() 
        if pid > 0:
            # exit first parent
            sys.exit(0) 
    except OSError, e: 
        print >> sys.stderr, "fork #1 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1)

    # decouple from parent environment
    os.chdir("/") 
    os.setsid() 
    os.umask(0) 

    # do second fork
    try: 
        pid = os.fork() 
        if pid > 0:
            # exit from second parent, print eventual PID before
            print >> sys.stderr, "Daemon PID %d" % pid
            sys.exit(0) 
    except OSError, e: 
        print >> sys.stderr, "fork #2 failed: %d (%s)" % (e.errno, e.strerror) 
        sys.exit(1) 

    try:
        pidfilename = "/var/run/%s.pid" % os.path.basename(__file__)
        pidfile = open(pidfilename, "w")
        pidfile.write(str(os.getpid()))
        pidfile.close()
        atexit.register(lambda : os.remove(pidfilename))
    except IOError:
        print >> sys.stderr, "Could not open pid file"
        sys.exit(0) 

    # Redirect standard file descriptors.
    sys.stdout.flush()
    sys.stderr.flush()

    devnull = "/dev/null"
    stdin = devnull
    stdout = devnull
    stderr = devnull

    si = open(stdin, 'r')
    so = open(stdout, 'a+')
    se = open(stderr, 'a+', 0)
    os.dup2(si.fileno(), sys.stdin.fileno())
    os.dup2(so.fileno(), sys.stdout.fileno())
    os.dup2(se.fileno(), sys.stderr.fileno())

def main():
    # Setup the command line arguments.
    optp = optparse.OptionParser()

    # options.
    optp.add_option("-d", "--daemon", dest="daemon",
                    help="daemonize.", action="store_true")

    optp.add_option("-v", "--verbose", dest="verbose",
                    help="log verbosity.", action="store_true")

    optp.add_option("-c", "--conf", dest="conf",
                    help="configuration file.")

    opts, args = optp.parse_args()

    if opts.conf is None:
        print >> sys.stderr, "conf file not provided"
        optp.print_help()
        sys.exit(1)
    else:
        opts.conf = os.path.abspath(opts.conf)

    if opts.verbose in (None, False):
        loglevel = logging.INFO
    else:
        loglevel = logging.DEBUG

    
    if opts.daemon:
        daemonize()
        # log to syslog in bg
    	logsys = handlers.SysLogHandler("/dev/log", handlers.SysLogHandler.LOG_USER)
    	logger.setLevel(loglevel)
    	logsys.setFormatter(logging.Formatter(FULLFORMAT))
    	logger.addHandler(logsys)

        logger.debug("daemonize")

    else:
        # log to stderr in fg
        logging.basicConfig(level=loglevel,
                            format=FULLFORMAT)

    logger.debug("watchdog")
    wg = Watchdog(opts.conf)
    wg.run()

if __name__ == "__main__":    
    main()
